name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@53751a9789c7351e4924f01fe68370252a4f1f18 # v2.4.1
        with:
          version: latest
      - uses: actions/setup-node@v3
      - run: pnpm i
      - run: pnpm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@53751a9789c7351e4924f01fe68370252a4f1f18 # v2.4.1
        with:
          version: latest
      - uses: actions/setup-node@v3
      - run: pnpm i
      - run: pnpm run build
      - run: pnpm run test
